apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cp4apps-git
  namespace: kabanero
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/kabanero-demo/nodejs-express-ocp42
