apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: c4apps-image
  namespace: kabanero
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/kabanero/nodejs-express-ocp42
