apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  annotations:
  name: node-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: build-push-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
        outputs:
          - name: docker-image
            resource: docker-image
      taskRef:
        name: nodejs-express-build-push-task
    - name: image-scan-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
          - name: docker-image
            resource: docker-image
      runAfter:
        - build-push-task
      taskRef:
        name: nodejs-express-image-scan-task
    - name: deploy-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
          - name: docker-image
            resource: docker-image
      runAfter:
        - build-push-task
      taskRef:
        name: nodejs-express-deploy-task
